version: '3'
services:
  nginx:
   container_name: school-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 81:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - institution
  
  school-mongo:
    container_name: "school-mongo"
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  
  institution:
    restart: always
    build: ./institution
    working_dir: /institution
    volumes:
      - ./institution:/institution
    expose:
      - "8081"
    command: mvn clean spring-boot:run
    links:
      - school-mongo