spring:
    #data.mongodb.database: school-db
    #data.mongodb.port: 27017
    #spring.data.mongodb.host: localhost
    data.mongodb.host: school-mongo
    rabbitmq.host: 127.0.0.1
    rabbitmq.port: 5672
    rabbitmq.username: guest
    rabbitmq.password: guest
    mail:
      host: smtp.gmail.com
      username: gomadsolutions@gmail.com
      password: Vulpix@17
      port: 587
      properties:
        mail:
          smtp:
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
            auth: true
            starttls:
              enable: true
              required: true
      protocol: smtp
      test-connection: true



amazonProperties:
  endpointUrl:
  accessKey:
  secretKey:
  bucketName: 
jwt:
  clientId: school
  client-secret: secret
  accessTokenValidititySeconds: 100
  refreshTokenValiditySeconds: 1000

server:
  port : 8081


logging:
  level:
    root: ERROR
    org.springframework.web: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.institution: TRACE