spring:
    #data.mongodb.host: school-db
    #data.mongodb.host: school-mongo
    data.mongodb.port: 27017
    data.mongodb.host: localhost
    data.mongodb.database: school-mongo
    #data.mongodb.uri: mongodb://root:root123@ds019470.mlab.com:19470/school-db?retryWrites=falsego
    #data.mongodb.uri: mongodb://development:secret@13.58.111.197/school-db
    rabbitmq.host: localhost
    rabbitmq.port: 5672
    rabbitmq.username: guest
    rabbitmq.password: guest
    mail:
      host: smtp.gmail.com
      username: gomadsolutions@gmail.com
      password: Vulpix@17
      port: 587
      properties:
        mail:
          smtp:
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
            auth: true
            starttls:
              enable: true
              required: true
      protocol: smtp
      test-connection: false



amazonProperties:
  endpointUrl:
  accessKey:
  secretKey:
  bucketName:
jwt:
  clientId: school
  client-secret: secret
  accessTokenValidititySeconds: 100
  refreshTokenValiditySeconds: 1000

server:
  port : 8081


logging:
  level:
    root: ERROR
    org.springframework.web: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.institution: TRACE